### ISSUE TITLE
Incorrect smm links in demo

### ISSUE THREAD

**Issue by DeFi-Evangelist** [Gravity-Tech/gravity-explorer-ui#3]
Incorrect social links in the footer.

Screenshot:
https://prnt.sc/tlpw3h

**Comment by sapranidi** [comment]
[Privacy policy](https://explorer.gravity.tech/docs/privacy-policy) and [Terms & Conditions](https://explorer.gravity.tech/docs/terms-of-use) are unaccessible at explorer.gravity.tech
